version: '3'
services:
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - myapp:/data/db
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - mongodb